spring:
 eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 application:
  name: todo-list
 jpa:
  show_sql: true
 h2:
  console:
   enabled: true 
   path: /h2-console
server:
 port: 8000

 